services:
  tfm-gpu:
    build:
      context: ..
      dockerfile: TFM_education_ai_analytics/Dockerfile
    volumes:
      - ..:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    entrypoint: [ "/bin/bash", "/workspace/TFM_education_ai_analytics/entrypoint.sh" ]
    command: [ "tail", "-f", "/dev/null" ]
    restart: unless-stopped
    ports:
      - "8888:8888" # Expose Jupyter port if needed
