services:
  tfm-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace/TFM_education_ai_analytics
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    entrypoint: [ "/bin/bash", "/workspace/TFM_education_ai_analytics/entrypoint.sh" ]
    command: [ "tail", "-f", "/dev/null" ]
    restart: unless-stopped
    ports:
      - "8888:8888" # Expose Jupyter port if needed
